name: Update Flake Inputs

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v31

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake inputs
        uses: mic92/update-flake-inputs@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          # Optional: exclude specific files or inputs
          # exclude-patterns: 'tests/**/flake.nix,examples/**/flake.nix#home-manager'
          # Optional: add custom labels (default: 'dependencies')
          # pr-labels: 'dependencies,automated'
          # Optional: enable auto-merge (default: false)
          auto-merge: 'true'
